<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bankTransfer" nsURI="http://www.example.org/bankTransfer" nsPrefix="bankTransfer">
  <eClassifiers xsi:type="ecore:EClass" name="Konto">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iban" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kontostand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inhaber" upperBound="3"
        eType="#//Inhaber" eOpposite="#//Inhaber/konto"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waehrung" eType="#//Waehrung"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inhaber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anschrift" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="telefonnummer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="konto" upperBound="-1"
        eType="#//Konto" eOpposite="#//Konto/inhaber"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Waehrung">
    <eLiterals name="EURO"/>
    <eLiterals name="USDOLLAR" value="1"/>
    <eLiterals name="SEK" value="2"/>
    <eLiterals name="NOK" value="3"/>
  </eClassifiers>
</ecore:EPackage>
