<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bankTransfer" nsURI="http://www.example.org/bankTransfer" nsPrefix="bankTransfer">
  <eClassifiers xsi:type="ecore:EClass" name="BankAccount">
    <eOperations name="sendMoney">
      <eParameters name="recipientIban" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="currency" eType="#//Currency"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iban" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bic" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accountBalance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" upperBound="3" eType="#//Owner"
        eOpposite="#//Owner/bankAccount"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currency" lowerBound="1"
        eType="#//Currency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Owner">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adress" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bankAccount" upperBound="-1"
        eType="#//BankAccount" eOpposite="#//BankAccount/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Currency">
    <eLiterals name="EUR"/>
    <eLiterals name="USD" value="1" literal="USD"/>
    <eLiterals name="SEK" value="2"/>
    <eLiterals name="NOK" value="3"/>
  </eClassifiers>
</ecore:EPackage>
